---
- hosts: lxplus9
  gather_facts: true

  tasks:
    - block:
        - name: Renew token
          environment: "{{ os_vars }}"
          shell: openstack token issue -c id -f value
          register: token
        - set_fact: openstack_token="{{ token.stdout }}"
  tags: always

- hosts: local
  connection: local
  tasks:
    - name: Update local token
      shell: "kubectl config set-credentials cmsrucioprod --token={{ hostvars['lxplus9']['openstack_token'] }}"
      register: out
  tags: local

- hosts: cern_vm
  tasks:
    - name: Update remote vm token
      shell: "kubectl config set-credentials cmsrucioprod --token={{ hostvars['lxplus9']['openstack_token'] }}"
  tags: remote
